version: "3"

services:

  nginx-server:
    image: nginx:alpine
    container_name: rcdocs
    # expose:
    #   - 8002
    ports:
      - "9001:80"
    volumes:
      - ./site:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      - mkdocs
    command: ash -c "rm /etc/nginx/conf.d/default.conf; nginx -g 'daemon off;'"

  mkdocs:
    build:
      context: ./
      dockerfile: Dockerfile
    # The name for the custom image being built
    image: python:mkdocs
    container_name: mkdocs
    volumes:
      - ./:/mkdocs_build
