site_name: Swinburne Research Cloud Quickstart Guide
site_url: https://supercomputing.swin.edu.au/rcdocs/
repo_url: null
# repo_name:
# edit_uri:
site_description: "A guide for quickly getting set up with a virtual machine on Nectar"
site_author: null
copyright: null
# google_analytics:
# remote_branch:
# remote_name:

markdown_extensions:
  - admonition
  - attr_list

theme:
  name: readthedocs
  custom_dir: theme_mods/
  custom_options:
    logos: true
    logos_only: true
  highlightjs: true
  hljs_languages:
      - bash
      - python
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  collapse_navigation: true
  titles_only: false
  sticky_navigation: true

nav:
  - Home: 'index.md'

  - Quickstart:
    - Get started: 'getting-started.md'
    - Security groups: 'security-groups.md'
    - SSH keys: 'ssh-key.md'
    - Launching an instance: 'launching-instance.md'
    - Accessing your instance: 'accessing-instance.md'

  - Astronomy users:
    - Astronomy projects/applications: 'astronomy.md'

  - Other useful tips:
    - Hosts + SSH config: 'ssh-config.md'
    - GUIs + X11 forwarding: 'gui-x11.md'
    - Viewing jupyter notebooks: 'jupyter-notebooks.md'
    - Adding project members: 'members.md'

  - Advanced workflows:
    - Volumes: 'volumes.md'
    - DNS: 'dns.md'
    - Networks: 'networks.md'
    - APIs + CLI: 'apis_cli.md'
    - Cloud Automation: 'automation.md'
